CREATE TABLE FIWARE_MARKETPLACE
(
    ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(255) NOT NULL,
    URL TEXT NOT NULL
);
CREATE TABLE SERVICE_PROVIDER
(
    ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(255) NOT NULL
);
CREATE TABLE TRUSTED_MARKETPLACE
(
    ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    SERVICE_PROVIDER_ID INT NOT NULL,
    TRUSTED_MARKETPLACE_ID INT NOT NULL
);
CREATE UNIQUE INDEX unique_ID ON FIWARE_MARKETPLACE ( ID );
CREATE UNIQUE INDEX unique_NAME ON FIWARE_MARKETPLACE ( NAME );
CREATE UNIQUE INDEX unique_ID ON SERVICE_PROVIDER ( ID );
CREATE UNIQUE INDEX unique_NAME ON SERVICE_PROVIDER ( NAME );
ALTER TABLE TRUSTED_MARKETPLACE ADD FOREIGN KEY ( SERVICE_PROVIDER_ID ) REFERENCES service_provider ( ID );
ALTER TABLE TRUSTED_MARKETPLACE ADD FOREIGN KEY ( TRUSTED_MARKETPLACE_ID ) REFERENCES fiware_marketplace ( ID );
CREATE UNIQUE INDEX ID ON TRUSTED_MARKETPLACE ( ID );
CREATE UNIQUE INDEX unique_ID ON TRUSTED_MARKETPLACE ( ID );
